server:
  port: 8080
  servlet:
    context-path: /srserverapi/
spring:
  profiles:
    active: dev
mybatis:
  config-location: classpath:mybatis-config.xml
logging:
  config: classpath:logback-boot.xml
